name: argocd-badges-api

on:
  push:
    branches:
      - develop
    paths:
      - 'app/**'
      - '.github/workflows/demo.yaml'

env:
  REPO_APP: 'argocd-badges-api'
  BUILD_CONTEXT: './app'
  COMMITER_NAME: 'AutoCommit'
  VULN_SEVERITY: 'CRITICAL,HIGH'
  VULN_TYPE: 'os,library'
  VULN_FORMAT: 'table'
  VULN_TIMEOUT_SCAN: '2m0s'
  VULN_SCANNERS: 'vuln,secret,misconfig,license'
  VULN_IGNORED_LIC: 'MIT'
  VULN_EXIT_CODE: 1
  TRIVY_DISABLE_VEX_NOTICE: true
  TRIVY_REPOSITORY: 'public.ecr.aws/aquasecurity/trivy-db:2'
  GH_REPO_OWNER: ${{ github.repository_owner }}
  GH_REPO_NAME: ${{ github.event.repository.name }}
  GH_REPO_BRANCH: ${{ github.ref_name }}
  SLACK_SECURITY_CHANNEL: 'security_issues'
  SLACK_BUILD_CHANNEL: 'builds'
  SLACK_MSG_COLOR: '#0092ff'


jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      actions: write


    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.GH_REPO_OWNER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN_FORGITHUB_ACTIONS }}

      - name: Build Docker image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.BUILD_CONTEXT }}
          push: true
          load: true
          tags: ${{ github.repository_owner }}/${{ env.GH_REPO_NAME }}:latest

      - name: Install Trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy -y

      - name: Run Trivy vulnerability scan
        id: trivy_scan
        continue-on-error: true
        run: |
          mkdir -p ./vuln_scans
          trivy image \
            --scanners ${{ env.VULN_SCANNERS }} \
            --severity ${{ env.VULN_SEVERITY }} \
            --timeout ${{ env.VULN_TIMEOUT_SCAN }} \
            --pkg-types ${{ env.VULN_TYPE }} \
            --license-full \
            --ignored-licenses ${{ env.VULN_IGNORED_LIC }} \
            --format ${{ env.VULN_FORMAT }} \
            --exit-code ${{ env.VULN_EXIT_CODE }} \
            --db-repository ${{ env.TRIVY_REPOSITORY }} \
            --ignore-unfixed \
            -o ./vuln_scans/${{ env.GH_REPO_NAME }}_vuln_scan.table \
            ${{ github.repository_owner }}/${{ env.GH_REPO_NAME }}:latest

      - name: Show Trivy report
        run: cat ./vuln_scans/${{ env.GH_REPO_NAME }}_vuln_scan.table

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install semantic-release
        run: npm install semantic-release @semantic-release/git @semantic-release/github @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/changelog

      - name: Run semantic-release (update CHANGELOG.md & GitHub release)
        id: semantic
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get latest release version
        id: get_version
        run: |
          VERSION=$(curl -s -m 10 --connect-timeout 5 \
            "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r .tag_name)
          if [ "$VERSION" = "null" ] || [ -z "$VERSION" ]; then
            echo "No release found, setting VERSION=v0.0.1"
            VERSION="v0.0.1"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Push Docker exact version
        id: docker_push_version
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.BUILD_CONTEXT }}
          push: true
          tags: ${{ github.repository_owner }}/${{ env.GH_REPO_NAME }}:${{ steps.get_version.outputs.version }}


      - name: validate if exist vuln
        if: ${{ steps.trivy_scan.outcome == 'failure' }}
        run: |
          echo "### See detailed information in: " > /tmp/vuln_info.md
          echo "<br>![](https://custom-icon-badges.demolab.com/badge/Vulnerability-detected-red.svg) ![](https://custom-icon-badges.demolab.com/badge/Affected_version-${{ steps.get_version.outputs.version }}-purple.svg) <br>" >> /tmp/vuln_info.md
          echo " * Detected in image: [${{ env.REPO_APP }}](https://hub.docker.com/repository/docker/${{ github.repository_owner }}/${{ env.GH_REPO_NAME }}/general)" >> /tmp/vuln_info.md
          echo " * Detected in commit: ${{ github.sha }}"  >> /tmp/vuln_info.md
          echo " * Vulnerability report: [vuln_report](https://github.com/${{ github.repository_owner }}/${{ env.GH_REPO_NAME }}/blob/${{ env.GH_REPO_BRANCH }}/vuln_scans/${{ env.REPO_APP }}_vuln_scan.table)" >> /tmp/vuln_info.md


      - name: update data
        if: ${{ steps.trivy_scan.outcome == 'failure' }}
        run: |
            git pull


      - name: Upload vuln scan report
        uses: EndBug/add-and-commit@v9
        with:
          message: 'AutoCommit: upload vuln scan report'
          add: './vuln_scans/${{ env.GH_REPO_NAME }}_vuln_scan.table'


      - name: Vulnerability detected - Create issue
        if: ${{ steps.trivy_scan.outcome == 'failure' }}
        run: |
          body="New vulnerability detected on vuln_scans/${{ env.REPO_APP }}_vuln_scan.table"
          gh issue create \
          --repo ${{ github.repository }} \
          --title ":skull: [vuln] vulnerability detected on image ${{ env.REPO_APP }} " \
          --body-file '/tmp/vuln_info.md' \
          --assignee "jpradoar" \
          --label bug
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Slack docker build Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: ${{ env.SLACK_BUILD_CHANNEL}}
          SLACK_COLOR: ${{ env.SLACK_MSG_COLOR }}
          SLACK_MESSAGE: 'URL: https://hub.docker.com/repository/docker/${{ env.GH_REPO_OWNER }}/${{ env.REPO_APP }}'
          SLACK_TITLE: ':rocket: GithubAction Build docker image: [ ${{ env.GH_REPO_NAME }}:${{ steps.get_version.outputs.version }} ]'
          SLACK_WEBHOOK: ${{ secrets.SLACK_BUILDS }}


      - name: Slack Vulnerability Notification
        if: ${{ steps.trivy_scan.outcome == 'failure' }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: ${{ env.SLACK_SECURITY_CHANNEL}}
          SLACK_COLOR: ${{ env.SLACK_MSG_COLOR }}
          SLACK_MESSAGE: 'URL: https://hub.docker.com/repository/docker/${{ env.GH_REPO_OWNER }}/${{ env.REPO_APP }}'
          SLACK_TITLE: ':skull: Vulnerability detected in: [ ${{ env.GH_REPO_NAME }}:${{ steps.get_version.outputs.version }} ]'
          SLACK_WEBHOOK: ${{ secrets.SLACK_SECURITY_ISSUES }}


      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pull latest changes
        run: git pull origin ${{ env.GH_REPO_BRANCH }}

      - name: Upload vuln scan report
        uses: EndBug/add-and-commit@v9
        with:
          message: 'AutoCommit: upload vuln scan report'
          add: './vuln_scans/${{ env.GH_REPO_NAME }}_vuln_scan.table'
